# You can add a "networks:" section here if you want. I chose not to, so 
# docker will create a default-network for this stack. 


services:
  redbot:

    # Simply the name of the service
    container_name: redbot

    # The docker-image which will be getting pulled. You can exchange "latest" to a specific version  
    image: phasecorex/red-discordbot:latest

    # Define this volume in the .env-file 
    volumes:
      - ${PATH_TO_DATA}:/data


    environment:
      # Define this in the .env-file as well. You can get this on the discord-developer-website. 
      - TOKEN=${BOT_TOKEN}
      # The prefix which the bot will listen on (e.g. ".play" or "/help")
      - PREFIX=.
      # Change this to your timezone
      - TZ=Europe/Berlin
      # The user the docker "use". Normally "PUID=1000" is your default user. 
      - PUID=1000
    
    # The service will always try to restart, except you stopped manually 
    restart: unless-stopped




